_wandb:
    value:
        cli_version: 0.19.1
        code_path: code/sac_continuous_action.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
alpha:
    value: 0.2
autotune:
    value: true
batch_size:
    value: 32
buffer_size:
    value: 1000000
capture_video:
    value: true
cuda:
    value: true
env_id:
    value: QuadEnv
exp_name:
    value: sac_continuous_action
gamma:
    value: 0.99
learning_starts:
    value: 5000
policy_frequency:
    value: 2
policy_lr:
    value: 0.0003
q_lr:
    value: 0.001
seed:
    value: 1
target_network_frequency:
    value: 1
tau:
    value: 0.005
torch_deterministic:
    value: true
total_timesteps:
    value: 1000000
track:
    value: true
video_freq:
    value: 50
wandb_entity:
    value: null
wandb_project_name:
    value: Quad_Mujoco
