[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rl_quad"]

[project]
name = "rl_quad"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "numpy==2.1.3",
]
