_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[ 0.58856443 -0.08301994 -0.0102525   0.08357333  1.06130742 -0.07783117
          -0.00969409  0.05152107  0.07048398 -0.09569715 -0.03844477 -0.03893168
          -0.07224444  0.09926258  0.06668657  0.02753368  0.0212713  -0.03960466
           0.05021695 -0.0966469  -0.01760882 -0.15130267 -0.24296544 -0.05218085
          -0.08345604 -0.16738349  0.15194147  0.09320122 -0.00790192  0.08280472
           0.00290859  0.08691377  0.12635556 -0.02384589  0.03454384  0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.          0.
           0.          0.          0.          0.          0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7e2260f39fc0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 5000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/run_experiments.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 3
                - 13
                - 22
                - 23
                - 35
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box(-6.28, 6.28, (12,), float32)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7e2260f51630>
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7e226b2e4b50>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7e226a7c69e0>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (113,), float64)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=113, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=113, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=12, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7e226a7be680>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1733157733966723982
target_kl:
    value: None
tensorboard_log:
    value: runs/PPO
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
